server:
  port: 8085

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5436/inventory_db}
    username: ${INVENTORY_DB_USER:admin}
    password: ${INVENTORY_DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
