server:
  port: 8087

spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5437/order_db}
    username: ${ORDER_DB_USER:admin}
    password: ${ORDER_DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
