server:
  port: 8092

spring:
  application:
    name: warehouse-service
  datasource:
    url: ${DB_URL:jdbc:h2:mem:warehouse_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  gateway:
    secret: ${GATEWAY_SECRET:platform_default_gateway_shared_secret}
